/*
 * This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at https://mozilla.org/MPL/2.0/.
 */

package au.org.ala.search.service.remote;

import au.org.ala.search.model.quality.QualityCategory;
import au.org.ala.search.model.quality.QualityFilter;
import au.org.ala.search.model.quality.QualityProfile;
import au.org.ala.search.repo.DataQualityPostgresRepository;
import com.fasterxml.jackson.databind.ObjectMapper;
import jakarta.annotation.PostConstruct;
import lombok.Getter;
import lombok.extern.slf4j.Slf4j;
import org.apache.commons.io.FileUtils;
import org.apache.commons.lang3.StringUtils;
import org.springframework.cache.CacheManager;
import org.springframework.cache.annotation.Cacheable;
import org.springframework.scheduling.annotation.Scheduled;
import org.springframework.stereotype.Service;

import java.io.File;
import java.io.IOException;
import java.util.*;
import java.util.concurrent.CountDownLatch;
import java.util.concurrent.atomic.AtomicLong;

/**
 * Quality data service for managing quality profiles, categories, and filters.
 * - The majority of the methods have caching.
 * - Only the leader instance can safely write to the database.
 *
 * Future: Due to the legacy data quality ids required and choice to now use a single db table, all data changes are
 * coordinated through the leader instance. If this ends up causing too many issues for admin edits it can be
 * refactored into multiple tables so that the ids are generated by the database, or, by removing the category and
 * filter id requirement when the legacy API is no longer needed.
 *
 */
@Slf4j
@Service
public class QualityDataService {

    protected final DataQualityPostgresRepository dataQualityRepository;
    protected final CacheManager cacheManager;
    protected final StaticFileStoreService staticFileStoreService;
    final Object editLock = new Object();
    final private AtomicLong uniqueId = new AtomicLong(1);
    @Getter
    volatile List<QualityProfile> profiles;
    private CountDownLatch cacheRefreshLatch = new CountDownLatch(0);

    public QualityDataService(DataQualityPostgresRepository dataQualityRepository, CacheManager cacheManager, StaticFileStoreService staticFileStoreService) {
        this.dataQualityRepository = dataQualityRepository;
        this.cacheManager = cacheManager;
        this.staticFileStoreService = staticFileStoreService;
    }

    private Long nextId() {
        return uniqueId.getAndAdd(1);
    }

    @PostConstruct
    void init() {
        cacheRefresh();
    }

    private String invert(String query) {
        if (StringUtils.isNotEmpty(query)) {
            if (query.startsWith("-")) {
                return query.substring(1);
            } else {
                return "-" + query;
            }
        }
        return "-(" + query + ")";
    }

    // If expecting a call cacheRefresh(), set the latch to 1 or just return it
    public synchronized CountDownLatch getCacheRefreshLatch() {
        if (cacheRefreshLatch.getCount() == 0) {
            cacheRefreshLatch = new CountDownLatch(1);
        }
        return cacheRefreshLatch;
    }

    /**
     * Need to call on startup, on requested cache refresh, periodically in case a broadcast message is missed,
     * a short time after startup for the same reason, and before writing to the database so the local id is correct.
     */
    @Scheduled(fixedRate = 60 * 60 * 1000, initialDelay = 60 * 1000)
    public void cacheRefresh() {
        // read from postgres, all profiles
        profiles = dataQualityRepository.findAllNative();

        // fetch the max id from the profiles, categories and filters. Only relevant for the leader instance.
        long maxId = 1;
        for (QualityProfile profile : profiles) {
            if (profile.getId() != null && profile.getId() > maxId) {
                maxId = profile.getId();
            }
            for (QualityCategory category : profile.getCategories()) {
                if (category.getId() != null && category.getId() > maxId) {
                    maxId = category.getId();
                }
                for (QualityFilter filter : category.getQualityFilters()) {
                    if (filter.getId() != null && filter.getId() > maxId) {
                        maxId = filter.getId();
                    }
                }
            }
        }
        uniqueId.set(maxId + 1);

        cacheManager.getCache("qualityProfiles").clear();

        // signal latch
        cacheRefreshLatch.countDown();
    }

    public List<QualityProfile> getProfiles(String shortName, String name, Boolean enabled, Integer max, Integer offset, String sort, String order) {
        List<QualityProfile> profiles = this.profiles;

        List<QualityProfile> list = new ArrayList<>();

        for (QualityProfile profile : profiles) {
            if (StringUtils.isNotBlank(shortName) && !profile.getShortName().equals(shortName)) {
                continue;
            }
            if (StringUtils.isNotBlank(name) && !profile.getName().equals(name)) {
                continue;
            }
            if (enabled != null && profile.isEnabled() != enabled) {
                continue;
            }

            list.add(profile);
        }

        if (StringUtils.isNotEmpty(sort) && StringUtils.isNotEmpty(order)) {
            int direction = order.equalsIgnoreCase("desc") ? -1 : 1;
            list.sort((a, b) -> {
                return switch (sort) {
                    case "id" -> a.getId().compareTo(b.getId()) * direction;
                    case "shortName" -> a.getShortName().compareTo(b.getShortName()) * direction;
                    case "name" -> a.getName().compareTo(b.getName()) * direction;
                    case "dateCreated" -> a.getDateCreated().compareTo(b.getDateCreated()) * direction;
                    case "lastUpdated" -> a.getLastUpdated().compareTo(b.getLastUpdated()) * direction;
                    case "displayOrder" -> a.getDisplayOrder().compareTo(b.getDisplayOrder()) * direction;
                    default -> 0;
                };
            });
        }

        if (offset >= list.size()) {
            return new ArrayList<>();
        }

        return list.subList(offset, Math.min(list.size(), offset + max));
    }

    @Cacheable(value = "qualityProfiles", key = "'getProfile_' + #profileId")
    public QualityProfile getProfile(String profileId) {
        List<QualityProfile> profiles = this.profiles;
        Optional<QualityProfile> profile = profiles.stream().filter(p -> p.getId().toString().equals(profileId) || p.getShortName().equals(profileId)).findFirst();
        return profile.orElse(null);
    }

    @Cacheable(value = "qualityProfiles", key = "'getCategory_' + #profileId + '_' + #categoryId")
    public QualityCategory getCategory(String profileId, Long categoryId) {
        List<QualityProfile> profiles = this.profiles;
        Optional<QualityProfile> profile = profiles.stream().filter(p -> p.getId().toString().equals(profileId) || p.getShortName().equals(profileId)).findFirst();
        if (profile.isPresent()) {
            Optional<QualityCategory> category = profile.get().getCategories().stream().filter(it -> it.getId().equals(categoryId)).findFirst();
            return category.orElse(null);
        }
        return null;
    }

    @Cacheable(value = "qualityProfiles", key = "'getFilter_' + #profileId + '_' + #categoryId + '_' + #id")
    public QualityFilter getFilter(String profileId, Long categoryId, Long id) {
        List<QualityProfile> profiles = this.profiles;
        Optional<QualityProfile> profile = profiles.stream().filter(p -> p.getId().toString().equals(profileId) || p.getShortName().equals(profileId)).findFirst();
        if (profile.isPresent()) {
            Optional<QualityCategory> category = profile.get().getCategories().stream().filter(it -> it.getId().equals(categoryId)).findFirst();
            if (category.isPresent()) {
                Optional<QualityFilter> filter = category.get().getQualityFilters().stream().filter(it -> it.getId().equals(id)).findFirst();
                return filter.orElse(null);
            }
        }
        return null;
    }

    @Cacheable(value = "qualityProfiles", key = "'getProfileOrDefault_' + #profileName")
    public QualityProfile getProfileOrDefault(String profileName) {
        List<QualityProfile> profiles = this.profiles;
        int id = StringUtils.isNumeric(profileName) ? Integer.parseInt(profileName) : 0;
        Optional<QualityProfile> profile = StringUtils.isNotEmpty(profileName) ?
                profiles.stream().filter(p -> p.getShortName().equals(profileName) || p.getName().equals(profileName) || p.getId() == id).findFirst() :
                Optional.empty();

        if (profile.isEmpty()) {
            return profiles.stream().filter(q -> q.isDefault()).findFirst().orElse(null);
        }
        return profile.get();
    }

    @Cacheable(value = "qualityProfiles", key = "'getEnabledFiltersByLabel_' + #profileName")
    public Map<String, String> getEnabledFiltersByLabel(String profileName) {
        Map<String, String> map = new HashMap<>();

        QualityProfile profile = getProfileOrDefault(profileName);

        if (profile != null) {
            profile.getCategories().forEach(category -> {
                if (category.isEnabled()) {
                    List<String> filters = category.getQualityFilters().stream().filter(QualityFilter::isEnabled).map(QualityFilter::getFilter).toList();
                    if (!filters.isEmpty()) {
                        map.put(category.getLabel(), String.join(" AND ", filters));
                    }
                }
            });
        }

        return map;
    }

    @Cacheable(value = "qualityProfiles", key = "'getEnabledQualityFilters_' + #profileName")
    public Set<String> getEnabledQualityFilters(String profileName) {
        Set<String> set = new HashSet<>();

        QualityProfile profile = getProfileOrDefault(profileName);

        if (profile != null) {
            profile.getCategories().forEach(category -> {
                if (category.isEnabled()) {
                    category.getQualityFilters().stream().filter(QualityFilter::isEnabled).forEach(it -> set.add(it.getFilter()));
                }
            });
        }

        return set;
    }

    @Cacheable(value = "qualityProfiles", key = "'getGroupedEnabledFilters_' + #profileName")
    public LinkedHashMap<String, List<QualityFilter>> getGroupedEnabledFilters(String profileName) {
        LinkedHashMap<String, List<QualityFilter>> map = new LinkedHashMap<>();

        QualityProfile profile = getProfileOrDefault(profileName);

        if (profile != null) {
            profile.getCategories().forEach(category -> {
                if (category.isEnabled()) {
                    List<QualityFilter> filters = category.getQualityFilters().stream().filter(QualityFilter::isEnabled).toList();
                    if (!filters.isEmpty()) {
                        map.put(category.getLabel(), filters);
                    }
                }
            });
        }

        return map;
    }

    @Cacheable(value = "qualityProfiles", key = "'findAllEnabledCategories_' + #profileName")
    public List<QualityCategory> findAllEnabledCategories(String profileName) {
        List<QualityCategory> result = new ArrayList<>();

        QualityProfile profile = getProfileOrDefault(profileName);

        if (profile != null) {
            profile.getCategories().forEach(category -> {
                if (category.isEnabled()) {
                    QualityCategory qc = QualityCategory.builder()
                            .id(category.getId())
                            .enabled(category.isEnabled())
                            .name(category.getName())
                            .label(category.getLabel())
                            .description(category.getDescription())
                            .displayOrder(category.getDisplayOrder())
                            .inverseFilter(category.getInverseFilter())
                            .qualityFilters(new ArrayList<>())
                            .build();
                    category.getQualityFilters().forEach(qf -> {
                        qc.getQualityFilters().add(QualityFilter.builder()
                                .id(qf.getId())
                                .enabled(qf.isEnabled())
                                .filter(qf.getFilter())
                                .description(qf.getDescription())
                                .displayOrder(qf.getDisplayOrder())
                                .build());
                    });
                    result.add(qc);
                }
            });
        }

        return result;
    }

    @Cacheable(value = "qualityProfiles", key = "'getJoinedQualityFilter_' + #profileName")
    public String getJoinedQualityFilter(String profileName) {
        return StringUtils.join(getEnabledQualityFilters(profileName), " AND ");
    }

    @Cacheable(value = "qualityProfiles", key = "'getInverseCategoryFilter_' + #qualityCategoryId")
    public String getInverseCategoryFilter(Long qualityCategoryId) {
        List<QualityProfile> profiles = this.profiles;
        List<QualityFilter> filters = new ArrayList<>();
        List<String> inverseFilter = new ArrayList<>();
        profiles.forEach(it -> {
            it.getCategories().forEach(category -> {
                if (category.getId().equals(qualityCategoryId)) {
                    if (StringUtils.isNotEmpty(category.getInverseFilter())) {
                        inverseFilter.add(category.getInverseFilter());
                    } else {
                        filters.addAll(category.getQualityFilters().stream().filter(QualityFilter::isEnabled).toList());
                    }
                }
            });
        });

        if (!inverseFilter.isEmpty()) {
            return inverseFilter.getFirst();
        }

        return StringUtils.join(filters.stream().map(it -> invert(it.getFilter())).toList(), " OR ");
    }

    @Cacheable(value = "qualityProfiles", key = "'getAllInverseCategoryFiltersForProfile_' + #qualityProfileId")
    public Map<String, String> getAllInverseCategoryFiltersForProfile(String qualityProfileId) {
        Map<String, String> result = new HashMap<>();

        QualityProfile profile = getProfileOrDefault(qualityProfileId);

        if (profile != null) {
            profile.getCategories().forEach(category -> {
                if (category.isEnabled()) {
                    if (StringUtils.isNotEmpty(category.getInverseFilter())) {
                        result.put(category.getLabel(), category.getInverseFilter());
                    } else {
                        List<QualityFilter> filters = category.getQualityFilters().stream().filter(QualityFilter::isEnabled).toList();

                        String inverse = StringUtils.join(filters.stream().map(it -> invert(it.getFilter())).toList(), " OR ");

                        result.put(category.getLabel(), inverse);
                    }
                }
            });
        }

        return result;
    }

    public boolean delete(Long profileId) {
        synchronized (editLock) {
            try {
                dataQualityRepository.deleteById(profileId);

                cacheRefresh();

                exportProfiles();

                return true;
            } catch (Exception e) {
                log.error("Error deleting profile", e);
                return false;
            }
        }
    }

    // Requests are from admin only, so there is a high level of trust in the data
    public QualityProfile save(QualityProfile profile) {
        List<QualityProfile> profiles = this.profiles;

        // Future: when no longer assigning an id to categories or filters, save() will no longer require a cacheRefresh() call.
        boolean cacheRefreshed = false;

        synchronized (editLock) {
            // ensure isDefault:true is unique
            if (profile.isDefault()) {
                // remove isDefault from all other profiles
                profiles.forEach(it -> {
                    if (it.isDefault() && !it.getId().equals(profile.getId())) {
                        it.setDefault(false);
                        dataQualityRepository.save(it);
                    }
                });
            } else {
                // do not remove isDefault from the last profile
                if (profiles.stream().noneMatch(q -> q.isDefault())) {
                    profile.setDefault(true);
                    profile.setEnabled(true); // the default must be enabled
                }
            }

            // update lastUpdated
            profile.setLastUpdated(new Date());

            // A legacy requirement is that QualityFilter.id and QualityCategory.id are unique, not null and not 0.
            if (profile.getCategories() != null) {
                for (QualityCategory category : profile.getCategories()) {
                    if (category.getQualityFilters() != null) {
                        for (QualityFilter filter : category.getQualityFilters()) {
                            if (filter.getId() == null || filter.getId() == 0) {
                                if (!cacheRefreshed) {
                                    cacheRefresh();
                                    cacheRefreshed = true;
                                }
                                filter.setId(nextId());
                            }
                        }
                        if (category.getId() == null || category.getId() == 0) {
                            if (!cacheRefreshed) {
                                cacheRefresh();
                                cacheRefreshed = true;
                            }
                            category.setId(nextId());
                        }
                    } else {
                        category.setQualityFilters(new ArrayList<>());
                    }
                }
            } else {
                profile.setCategories(new ArrayList<>());
            }

            // Remove placeholder profile.id=0. To be populated by postgres.
            if (profile.getId() == null || profile.getId() == 0) {
                if (!cacheRefreshed) {
                    cacheRefresh();
                    cacheRefreshed = true;
                }
                profile.setId(nextId());
            }

            // displayOrder must be present
            if (profile.getDisplayOrder() == null) {
                profile.setDisplayOrder((long) profiles.size());
            }

            QualityProfile duplicate = profiles.stream().filter(it -> it.getShortName().equals(profile.getShortName())).findFirst().orElse(null);
            if (duplicate != null && !duplicate.getId().equals(profile.getId())) {
                log.error("Profile with shortName {} already exists", profile.getShortName());
                return null;
            }

            try {
                QualityProfile savedProfile = dataQualityRepository.save(profile);

                cacheRefresh();

                exportProfiles();

                return savedProfile;
            } catch (Exception e) {
                log.error("Error saving profile", e);
                return null;
            }
        }
    }

    public void exportProfiles() throws IOException {
        List<QualityProfile> profiles = this.profiles;
        File tmpFile = File.createTempFile("qualityProfiles", ".json");
        FileUtils.writeStringToFile(tmpFile, new ObjectMapper().writeValueAsString(profiles), "UTF-8");
        staticFileStoreService.copyToFileStore(tmpFile, "dataQuality/profiles.json", true);
    }

    // fetch the profile by shortName from the database without caching
    public QualityProfile getProfileNow(String shortName) {
        List<QualityProfile> list = dataQualityRepository.findAllByShortName(shortName);
        if (list.isEmpty()) {
            return null;
        }
        return list.get(0);
    }
}
