version: '3.7'
services:
#  kibana:
#    image: docker.elastic.co/kibana/kibana:8.13.0-arm64
#    ports:
#      - "5601:5601"
# TODO: tidy up and document
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.0-arm64
    container_name: species-lists-elastic
    environment:
      - node.name=elasticsearch
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    volumes:
      - /data/species-lists/elastic:/usr/share/elasticsearch/data
    restart: on-failure
    ports:
      - "9200:9200"
      - "9300:9300"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://elasticsearch:9200" ]
      interval: 30s
      timeout: 10s
      retries: 5
volumes:
  elasticsearch-data:
    driver: local
