app.name=search-service
app.version=0.1-SNAPSHOT
server.port=8081
spring.threads.virtual.enabled=true
# Using elastic.host with prefix "https://" enables ssl
elastic.host=localhost:9200
# optional elasticsearch username and password
#elastic.username=
#elastic.password=
# general index, typically versioned in alignment with the DwCA names index
elastic.index=search-2024-04-30
# task logs
elastic.adminIndex=search-log-2024-04-30
elastic.timeout=1800000
elastic.pageSize=1000
spring.elasticsearch.socket-keep-alive=true
spring.elasticsearch.socket-timeout=600s
springdoc.swagger-ui.path=
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
# TODO: support disabling of security, e.g. for local use

# This is the domain for a cookie set by the service when a user logs in. It is readable by the client application to
# determine if a user is logged in.
security.cookie.name=ALA-SESSION
security.cookie.domain=ala.org.au
# create a debug cookie with details of when the secret cookie was created and from what origin
security.cookie.debug=false

# This is authentication provider's login session max age (refreshToken maxAge).
security.login.maxAgeDays=30

# cognito auth config
security.jwt.userIdClaim=username
security.jwt.roleClaims=cognito:groups
security.jwt.rolesFromAccessToken=true
security.oidc.logoutAction=COGNITO
security.oidc.scope=openid profile email ala/attrs ala/roles
security.oidc.userIdClaim=cognito:username
security.oidc.roleClaims=ala:role

# cas oidc auth config
#security.jwt.userIdClaim=userid
#security.jwt.roleClaims=role
#security.oidc.logoutAction=DEFAULT
#security.oidc.scope=openid profile email ala roles
#security.oidc.userIdClaim=userid
#security.oidc.roleClaims=role

# origins to include in Access-Control-Allow-Origin response header for login details
security.cors.origins=http://localhost:5173,http://localhost:8080,http://localhost:8081,https://doi2.test.ala.org.au,https://doi.test.ala.org.au

security.oidc.discovery-uri=
security.oidc.clientId=
security.oidc.secret=

security.jwt.enabled=true
security.jwt.discovery-uri=
security.jwt.clientId=
security.jwt.secret=
security.apikey.enabled=false
# admin role and admin scope
security.admin.role=ROLE_ADMIN,ala/internal
logging.level.au.org.ala.ws=WARN
#logging.level.tracer=TRACE
#logging.level.org.springframework=TRACE
#logging.level.com.baeldung=TRACE
wordpress.url=https://www.ala.org.au
wordpress.sitemap=/xmlsitemap.xml
wordpress.timeout=10000
wordpress.titleSelector=head > title
wordpress.contentSelector=body main
wordpress.contentOnlyParams=?content-only=1&categories=1
knowledgebase.url=https://support.ala.org.au
knowledgebase.sitemap=/support/sitemap.xml
knowledgebase.timeout=10000
lists.url=https://lists.ala.org.au
lists.uiUrl=https://lists.ala.org.au/speciesListItem/list/
lists.addPath=/ws/createItem
lists.removePath=/ws/deleteItem
collections.url=https://collections.ala.org.au
#userdetails.url=https://auth.ala.org.au/userdetails
userdetails.url=https://api.test.ala.org.au/userdetails/cognito/
biocollect.url=https://biocollect.ala.org.au
biocollect.search=/ws/project/search?initiator=ala
spatial.url=https://spatial.ala.org.au/ws
spatial.uiUrl=https://spatial.ala.org.au
spatial.layerPath=/layers/view/more/
# gazetteer layer id and ids of other layers worth importing, e.g. States and Territories, LGA, CAPAD, IBRA, IMCRA
spatial.layers=2123,10923,11033,21,10912,10921,10925,1048
dwca.dir=/data/bie/import
dwca.extract.leftRightCsvPath=/data/bie/lsid-left-right.csv
dwca.extract.commonNamePath=/data/bie/lsid-vernacularName.csv
taxonRanksFile=
commonName.defaultLanguage=en-AU
vernacularName.preferredStatus=preferred
vernacularName.common=common
biocache.url=https://biocache-ws.ala.org.au/ws
biocache.uiUrl=https://biocache.ala.org.au
image.url=https://images.test.ala.org.au
dashboard.summarySpeciesCountQuery=/occurrence/facets?q=country:Australia+OR+cl21:*&facets=species&fsort=count&flimit=0
lists.search.max=500
# comma delimited list
lists.images.ids=dr5363
lists.images.preferred.field=imageId
images.preferred.fqs=dataResourceUid:dr660 OR dataResourceUid:dr413,-basisOfRecord:PreservedSpecimen,*:*
images.required.fq=spatiallyValid:true AND -userAssertions:50001 AND -userAssertions:50005 AND -identificationVerificationStatus:needs_id
images.caching.threadpool.size=20

# ';' separated items of listId,string. e.g. dr4778,interest;dr781,iconic
# used in calculating searchWeight value used as a boost when searching to TAXON
# "interest" -> w *= 1.1;
# "preferred" -> w *= 1.5;
# "favourite" -> w *= 2.5;
# "iconic" -> w *= 10;
# To handle instances where a species appears on >1 list, put the higher preference first.
lists.favourite.config=dr781,iconic;dr4778,interest
lists.wiki.field=url
lists.conservation.statusField=status
lists.native-introduced=dr22795
# species group path; file or empty value for resources/speciesGroups.json
speciesGroup.path=
priority.min=0.25
priority.max=5.0
priority.norm=4000
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.UserDetailsServiceAutoConfiguration
# default 5 mins
webservice.read.timeout=600000
webservice.connect.timeout=600000
webservice.jwt=true
webservice.jwt-scopes=users/read ala/attrs ala/internal
webservice.client-id=<Add m2m client-id>
webservice.client-secret=<Add m2m client-secret>

# enable/disable tasks in case memory requirements are exceeded by the environment
# - default DWCA requires 4GB
# - default AREA requires 1GB
# - default others require 500MB
task.AREA.enabled=true
task.BIOCACHE.enabled=true
task.BIOCOLLECT.enabled=true
task.DIGIVOL.enabled=true
task.COLLECTIONS.enabled=true
task.DWCA.enabled=true
task.KNOWLEDGEBASE.enabled=true
task.LAYER.enabled=true
task.LISTS.enabled=true
task.SITEMAP.enabled=true
task.WORDPRESS.enabled=true
task.TAXON_DESCRIPTION.enabled=true
task.POSTGRES_SYNC.enabled=true
task.DASHBOARD.enabled=true
# Legacy mapping. This is the bie-index config value for conservationListsUrl.
conservation.mapping.path=/conservation-lists.json
# Languages mapping.
languages.path=/languages.json
attribution.default=National Species Lists
attribution.common=
attribution.synonym=
attribution.identifier=
attribution.variant=
#logging.level.root=TRACE
data.dir=/data/atlas-search
#bhl.ala.org.au=https://www.biodiversitylibrary.org/collection/bhlau
#bhl.url=https://bhl.ala.org.au
bhl.url=https://www.biodiversitylibrary.org/collection/bhlau
bhl.image.url=https://static.ala.org.au/images/bhl-logo-main.png
logger.url=https://logger.ala.org.au
images.url=https://images.ala.org.au
digivol.url=https://volunteer.ala.org.au
digivol.image.url=https://static.ala.org.au/images/logoDigivolInvertedRed.png
digivol.expeditionUrl=/ws/expeditionInfo
defaultDownloadFields=guid,rank,scientificName,scientificNameAuthorship,taxonomicStatus,establishmentMeans,datasetName,parentGuid,acceptedConceptName,acceptedConceptID,idxtype,name,additionalNames_m_s
# /api-docs endpoint custom path
springdoc.api-docs.path=/api-docs
# Disabling the swagger-ui
#springdoc.swagger-ui.enabled=false
openapi.title=Search Index API
openapi.description=REST services for interacting with the Search Index
openapi.terms=https://www.ala.org.au/terms
openapi.contact.name=Support
openapi.contact.email=
openapi.license.name=Mozilla Public License 1.1
openapi.license.url=https://www.mozilla.org/en-US/MPL/1.1/
openapi.version=@project.version@
# comma delimited server list. The first server is returned as the baseUrl for services such as /V2/download
openapi.servers=http://localhost:8081
# in addition to @Hidden annotations, also hide by path prefix, e.g. /api,/admin
openapi.paths.hidden=/api
spring.config.import=optional:file:/data/search-service/config/search-service-config.properties
# email configuration
spring.mail.host=localhost
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.transport.protocol=smtp
spring.mail.properties.mail.smtp.port=25
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false
spring.mail.properties.mail.smtp.starttls.required=false
# Static File store configuration.
# This is the destination of static files generated.
# These are to be accessed by UI clients.
# - local directory path, e.g. /data/search-service/static
# - s3 with region and system credentials, e.g. s3://bucket-name/optional-path
# - s3 with region, accessKey and secretKey, e.g. s3://bucket-name/optional-path
static.filestore.path=/data/search-service/static
static.s3.accessKey=
static.s3.secretKey=
static.s3.region=
# Download store configuration.
# This is the destination of files generated for download.
# - local directory path, e.g. /data/search-service/downloads
# - s3 with region and system credentials, e.g. s3://bucket-name/optional-path
# - s3 with region, accessKey and secretKey, e.g. s3://bucket-name/optional-path
download.filestore.path=/data/search-service/downloads
download.s3.accessKey=
download.s3.secretKey=
download.s3.region=
# Duration in minutes for the pre-signed URL
download.s3.duration=30
# Optional. Instead of a presigned URL, return a direct URL to the file. e.g. https://bucket-name.s3.amazonaws.com/optional-path
download.s3.directPath=
# Hero descriptions data store configuration.
# This is the destination of files generated for download.
# - local directory path, e.g. /data/search-service/data
# - s3 with region and system credentials, e.g. s3://bucket-name/optional-path
# - s3 with region, accessKey and secretKey, e.g. s3://bucket-name/optional-path
data.filestore.path=/data/search-service/data
data.s3.accessKey=
data.s3.secretKey=
data.s3.region=
data.file.hero.descriptions=hero-descriptions.json
data.path.description.override=/override-descriptions
# DOI File store configuration.
# This is the destination of doi files generated.
# - local directory path, e.g. /data/search-service/doi
# - s3 with region and system credentials, e.g. s3://bucket-name/optional-path
# - s3 with region, accessKey and secretKey, e.g. s3://bucket-name/optional-path
doi.filestore.path=/data/search-service/doi
doi.s3.accessKey=
doi.s3.secretKey=
doi.s3.region=
# Duration in minutes for the pre-signed URL
doi.s3.duration=30
# Optional. Instead of a presigned URL, return a direct URL to the file. e.g. https://bucket-name.s3.amazonaws.com/optional-path
doi.s3.directPath=
# Enable/disable DOI minting. Set to true to enable minting. Set to false for testing.
doi.minting.enabled=false
# Base UI URL for the DOI resolver. /doi/{id} will be appended to this URL.
doi.baseUrl=https://doi.test.ala.org.au
doi.publicationLang=en

# DataCite DOI service configuration
datacite.doi.service.baseApiUrl=https://api.test.datacite.org/
datacite.doi.service.user=
datacite.doi.service.password=
datacite.doi.service.prefix=
datacite.doi.service.shoulder=ala
# timeout in seconds
datacite.doi.service.timeout=30

# align with the refresh token expiry duration in seconds
server.servlet.session.timeout=2678400
# Database schema initialization mode
spring.session.jdbc.initialize-schema=embedded
spring.session.jdbc.schema=classpath:org/springframework/session/jdbc/schema-postgresql.sql
spring.session.jdbc.table-name=SPRING_SESSION

spring.datasource.url=jdbc:postgresql://localhost:5433/search
spring.datasource.username=atlas
spring.datasource.password=password
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.temp.use_jdbc_metadata_defaults=false
spring.datasource.hikari.transaction-isolation=TRANSACTION_READ_COMMITTED
spring.datasource.hikari.maximum-pool-size=30
spring.datasource.hikari.minimum-idle=10
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

# logging
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.flyway.locations=classpath:/flyway
spring.flyway.baseline-on-migrate=true
spring.flyway.schemas=public
spring.flyway.table=search_schema_version
# Disable flyway when using manual migrations, see /resources/flyway/*.sql
spring.flyway.enabled=true
#logging.level.org.flywaydb.core=DEBUG

exploreYourArea.url=https://biocache.ala.org.au/explore/your-area#$latitude|$longitude|12|ALL_SPECIES
downloadMaxRows=5000000
# To disable userdetail validation of email addresses use fieldguide.validateEmail=false
fieldguide.validateEmail=true
#logging.level.org.apache.fop=DEBUG
homeUrl=https://ala.org.au
fieldguide.email.enabled=false
email.from=support@ala.org.au
fieldguide.email.text.success=Your download is available on the URL:\
  <br><br>[url]<br><br>When using this field guide please use the following citation:\
  <br><br><cite>Atlas of Living Australia field guide generated from [query] accessed on [date].\
  </cite><br><br>More information can be found at\
  <a href='https://support.ala.org.au/support/solutions/articles/6000261662-citing-the-ala'>citing the ALA</a>.<br><br>"
fieldguide.email.subject.success=ALA Field Guide Download Complete - [filename]
# Path to field guide template directory. If not specified the default built-in template is used (/resources/templates/*)
# Not currently cached and suitable for dynamic reloading of templates without restarting the service. e.g. when
# modifying the template files during development.
#fieldguide.template.path=/data/search-service/templates
fieldguide.template.path=

spring.cache.jcache.config=classpath:ehcache.xml

austraits.url=http://traitdata.austraits.cloud.edu.au
dashboard.states=Australian Capital Territory,New South Wales,South Australia,Northern Territory,Western Australia,Victoria,Queensland,Tasmania
# Sitemap File store configuration.
# This is the destination of sitemap files generated.
# These are to be accessed by crawlers.
# - local directory path, e.g. /data/search-service/static
# - s3 with region and system credentials, e.g. s3://bucket-name/optional-path
# - s3 with region, accessKey and secretKey, e.g. s3://bucket-name/optional-path
sitemap.filestore.path=/data/search-service/static
sitemap.s3.accessKey=
sitemap.s3.secretKey=
sitemap.s3.region=
# Base URL for sitemap xml locations. It is used by the sitemap index
sitemap.url=https://bie.ala.org.au
# Base URL for species pages.
speciesUrlPrefix=https://bie.ala.org.au/species/

# cron for the in memory caches to be updated from external sources
collectory.cache.cron=0 0 0 * * *
list.cache.cron=0 0 0 * * *
#RabbitMQ config (disabled by default) set a host value to enable
rabbitmq.host=localhost
rabbitmq.port=5672
rabbitmq.username=atlas
rabbitmq.password=password
rabbitmq.exchange.broadcast=search-service-broadcast
rabbitmq.exchange.direct=search-service-direct
# Limit the number of concurrent user tasks
rabbitmq.task.concurrency=20
#logging.level.org.springframework.amqp=DEBUG
#logging.level.org.springframework.amqp.rabbit=DEBUG
#logging.level.com.rabbitmq=DEBUG

#
# kubernetes config (disabled by default)
#
# Enable by:
# - enabling the commented out spring.cloud.*
# - using the default managment.* values (below the non-kubernetes environment values)
# - restricting access to /actuator

# Uncomment these for kubernetes
#spring.cloud.kubernetes.leader.enabled=true
#spring.cloud.kubernetes.leader.namespace=search-namespace
#spring.cloud.kubernetes.leader.role: search-service-leader

# Non-kubernetes overrides, use the commented out values below for kubernetes
management.endpoints.enabled-by-default=false
management.endpoints.web.exposure.exclude=*
management.endpoints.web.discovery.enabled=false
# Defaults for kubernetes.
# Ensure /actuator is not public
#management.endpoints.enabled-by-default=true
#management.endpoints.web.exposure.include=info,health,liveness,readiness
#management.endpoints.web.discovery.enabled=true
#management.endpoint.health.probes.enabled=true

# Dynamic configuration is stored in the database. The default values used are sourced from this file.
dynamic-config-defaults.path=classpath:dynamic-config-defaults.properties

# general logging adjustments
logging.level.org.springframework.web.servlet.PageNotFound=ERROR

# nginx style logging, for when no similar Kubernetes logging is available
server.tomcat.accesslog.enabled=false
server.tomcat.accesslog.pattern=%h %l %u %t "%r" %s %b "%{Referer}i" "%{User-Agent}i"
server.tomcat.accesslog.directory=/data/search-service/logs
server.tomcat.accesslog.prefix=access
server.tomcat.accesslog.suffix=.log
server.tomcat.accesslog.rotate=true
server.tomcat.accesslog.checkExists=true
server.tomcat.accesslog.file-date-format=.yyyy-MM-dd
