#
# Scheduled Tasks Timing Configuration
#
# Configure cron expressions for scheduled tasks.
# These settings control if and when tasks are triggered automatically.
# This does not override the application.properties where tasks can be enabled or disabled.
#

# ES indexing tasks. ALL will trigger all other tasks. Enable separately if needed.
schedule.ALL.enabled=true
schedule.ALL.cron=0 0 11 * * ?
# excludes schedule.DWCA, this can only be run manually
#schedule.BIOCACHE.enabled=true
#schedule.BIOCACHE.cron=0 0 12 * * ?
#schedule.DIGIVOL.enabled=true
#schedule.DIGIVOL.cron=0 0 12 * * ?
#schedule.AREA.enabled=true
#schedule.AREA.cron=0 0 12 * * ?
#schedule.BIOCOLLECT.enabled=true
#schedule.BIOCOLLECT.cron=0 0 12 * * ?
#schedule.COLLECTIONS.enabled=true
#schedule.COLLECTIONS.cron=0 0 12 * * ?
#schedule.KNOWLEDGEBASE.enabled=true
#schedule.KNOWLEDGEBASE.cron=0 0 12 * * ?
#schedule.LAYER.enabled=true
#schedule.LAYER.cron=0 0 12 * * ?
#schedule.WORDPRESS.enabled=true
#schedule.WORDPRESS.cron=0 0 12 * * ?
#schedule.LISTS.enabled=true
#schedule.LISTS.cron=0 0 12 * * ?
#schedule.SITEMAP.enabled=true
#schedule.SITEMAP.cron=0 0 12 * * ?
# excludes schedule.TAXON_DESCRIPTION, this can only be run manually

# Dashboard data files update task.
schedule.DASHBOARD.enabled=true
schedule.DASHBOARD.cron=0 0 12 * * ?

# Cache reset tasks. CACHE_RESET_ALL resets all others. Enable separately if needed.
schedule.CACHE_RESET_ALL.enabled=true
schedule.CACHE_RESET_ALL.cron=0 0 6 * * ?
#schedule.CACHE_RESET_COLLECTORY.enabled=true
#schedule.CACHE_RESET_COLLECTORY.cron=0 0 12 * * ?
#schedule.CACHE_RESET_LISTS.enabled=true
#schedule.CACHE_RESET_LISTS.cron=0 0 12 * * ?
#schedule.CACHE_RESET_DATA_QUALITY.enabled=true
#schedule.CACHE_RESET_DATA_QUALITY.cron=0 0 12 * * ?
schedule.LOGGER_UPDATE_SUMMARY_TABLES.enabled=true
schedule.LOGGER_UPDATE_SUMMARY_TABLES.cron=0 0 * * * ?


